### ISSUE TITLE
KB3206632 on WS2019 17763 behaviour

### ISSUE THREAD

**Issue by github-tomster** [michelderooij/Install-Exchange15#7]
https://github.com/michelderooij/Install-Exchange15/blob/aba45c485430e2959c2ed236c4a19a82a58edf14/Install-Exchange15.ps1#L2787
https://github.com/michelderooij/Install-Exchange15/blob/aba45c485430e2959c2ed236c4a19a82a58edf14/Install-Exchange15.ps1#L2788
https://github.com/michelderooij/Install-Exchange15/blob/aba45c485430e2959c2ed236c4a19a82a58edf14/Install-Exchange15.ps1#L2789
https://github.com/michelderooij/Install-Exchange15/blob/aba45c485430e2959c2ed236c4a19a82a58edf14/Install-Exchange15.ps1#L2790
on server 2019 17763 the package is downloaded even though it is not applicable.
is that the expected behaviour?

**Comment by github-tomster** [comment]
well i looked at the changelog:
3.5 Corrected not installing KB3206632 on WS2019
i guess this fixes it?

**Comment by michelderooij** [comment]
Yes
